
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.HBox hbox3;
	
	private global::Gtk.Entry RemoteIP;
	
	private global::Gtk.HBox hbox4;
	
	private global::Gtk.Entry RemotePort;
	
	private global::Gtk.Entry LocalPort;
	
	private global::Gtk.Button button4;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	
	private global::Gtk.TextView MessagesView;
	
	private global::Gtk.HBox hbox2;
	
	private global::Gtk.Entry Message;
	
	private global::Gtk.Button SendMessage;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.RemoteIP = new global::Gtk.Entry ();
		this.RemoteIP.CanFocus = true;
		this.RemoteIP.Name = "RemoteIP";
		this.RemoteIP.Text = global::Mono.Unix.Catalog.GetString ("127.0.0.1");
		this.RemoteIP.IsEditable = true;
		this.RemoteIP.InvisibleChar = '●';
		this.hbox3.Add (this.RemoteIP);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.RemoteIP]));
		w1.Position = 0;
		// Container child hbox3.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox ();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.RemotePort = new global::Gtk.Entry ();
		this.RemotePort.CanFocus = true;
		this.RemotePort.Name = "RemotePort";
		this.RemotePort.Text = global::Mono.Unix.Catalog.GetString ("5001");
		this.RemotePort.IsEditable = true;
		this.RemotePort.InvisibleChar = '●';
		this.hbox4.Add (this.RemotePort);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.RemotePort]));
		w2.Position = 0;
		// Container child hbox4.Gtk.Box+BoxChild
		this.LocalPort = new global::Gtk.Entry ();
		this.LocalPort.CanFocus = true;
		this.LocalPort.Name = "LocalPort";
		this.LocalPort.Text = global::Mono.Unix.Catalog.GetString ("5002");
		this.LocalPort.IsEditable = true;
		this.LocalPort.InvisibleChar = '●';
		this.hbox4.Add (this.LocalPort);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.LocalPort]));
		w3.Position = 1;
		this.hbox3.Add (this.hbox4);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.hbox4]));
		w4.Position = 1;
		// Container child hbox3.Gtk.Box+BoxChild
		this.button4 = new global::Gtk.Button ();
		this.button4.CanFocus = true;
		this.button4.Name = "button4";
		this.button4.UseUnderline = true;
		this.button4.Label = global::Mono.Unix.Catalog.GetString ("Connect");
		this.hbox3.Add (this.button4);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.button4]));
		w5.Position = 2;
		w5.Expand = false;
		w5.Fill = false;
		this.vbox1.Add (this.hbox3);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox3]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.MessagesView = new global::Gtk.TextView ();
		this.MessagesView.CanFocus = true;
		this.MessagesView.Name = "MessagesView";
		this.MessagesView.CursorVisible = false;
		this.GtkScrolledWindow.Add (this.MessagesView);
		this.vbox1.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.GtkScrolledWindow]));
		w8.Position = 1;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.Message = new global::Gtk.Entry ();
		this.Message.CanFocus = true;
		this.Message.Name = "Message";
		this.Message.IsEditable = true;
		this.Message.InvisibleChar = '●';
		this.hbox2.Add (this.Message);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.Message]));
		w9.Position = 0;
		// Container child hbox2.Gtk.Box+BoxChild
		this.SendMessage = new global::Gtk.Button ();
		this.SendMessage.CanFocus = true;
		this.SendMessage.Name = "SendMessage";
		this.SendMessage.UseUnderline = true;
		this.SendMessage.Label = global::Mono.Unix.Catalog.GetString ("Send");
		this.hbox2.Add (this.SendMessage);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.SendMessage]));
		w10.Position = 1;
		w10.Expand = false;
		w10.Fill = false;
		this.vbox1.Add (this.hbox2);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
		w11.Position = 2;
		w11.Expand = false;
		w11.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 658;
		this.DefaultHeight = 382;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.button4.Clicked += new global::System.EventHandler (this.OnButton4Clicked);
		this.SendMessage.Clicked += new global::System.EventHandler (this.OnSendMessageClicked);
	}
}
